// Global object to store exactly one CSV dataset per slot
window.csvDataStore = {
    slotLeft: null,
    slotRight: null
};

const leftSlot = document.getElementById('left-slot');
const rightSlot = document.getElementById('right-slot');

// Prevent default drag behaviors for both slots
['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
    leftSlot.addEventListener(eventName, (e) => e.preventDefault(), false);
    rightSlot.addEventListener(eventName, (e) => e.preventDefault(), false);
});

document.getElementById('leftConvertBtn').addEventListener('click', () => {
    console.time("Tree Conversion Time");
    const finalTree = csvToTree(window.csvDataStore.slotLeft.data);
    window.csvDataStore.slotLeft["tree"] = finalTree
    console.timeEnd("Tree Conversion Time");
    window.csvDataStore.slotLeft.data = undefined
    console.log("Conversion successful! Resulting Tree Structure:", finalTree);
});
document.getElementById('rightConvertBtn').addEventListener('click', () => {
    console.time("Tree Conversion Time");
    const finalTree = csvToTree(window.csvDataStore.slotRight.data);
    window.csvDataStore.slotRight["tree"] = finalTree
    console.timeEnd("Tree Conversion Time");
    window.csvDataStore.slotRight.data = undefined
    console.log("Conversion successful! Resulting Tree Structure:", finalTree);
});
document.getElementById('diffBtn').addEventListener('click', () => {
    const diff = findTreeDifferences(csvDataStore.slotLeft.tree[0], csvDataStore.slotRight.tree[0])
    const diffTree = generateDiffTree(diff)
    computeAllocationDifference(diffTree)
    console.log(diff)
    window.diffResult = diff;
    console.log(diffTree)
    window.diffTreeResult = diffTree;
    sortDiffTreeBySize(diffTree);
    const existing = document.getElementById("diff-tree")
    if (existing !== null) {
        existing.parentElement.removeChild(existing);
    }
    document.body.appendChild(renderDiffTree(diffTreeResult))
});
document.getElementById('oneBtn').addEventListener('click', () => {
    if (!(window.csvDataStore.slotLeft.tree)) {
        const finalTree = csvToTree(window.csvDataStore.slotLeft.data);
        window.csvDataStore.slotLeft["tree"] = finalTree
        window.csvDataStore.slotLeft.data = undefined
    }
    if (!(window.csvDataStore.slotRight.tree)) {
        const finalTree = csvToTree(window.csvDataStore.slotRight.data);
        window.csvDataStore.slotRight["tree"] = finalTree
        window.csvDataStore.slotRight.data = undefined
    }
    const diff = findTreeDifferences(csvDataStore.slotLeft.tree[0], csvDataStore.slotRight.tree[0])
    const diffTree = generateDiffTree(diff)
    computeAllocationDifference(diffTree)
    // console.log(diff)
    // window.diffResult = diff;
    // console.log(diffTree)
    // window.diffTreeResult = diffTree;
    sortDiffTreeBySize(diffTree);
    const existing = document.getElementById("diff-tree")
    if (existing !== null) {
        existing.parentElement.removeChild(existing);
    }
    document.body.appendChild(renderDiffTree(diffTree))
});

// Event listener for the Left Slot
leftSlot.addEventListener('drop', (e) => {
    const file = e.dataTransfer.files[0];
    if (isValidCsv(file)) {
        readFile(file, 'slotLeft', leftSlot);
    } else {
        console.error("Please drop a valid CSV file into the Left slot.");
    }
});

// Event listener for the Right Slot
rightSlot.addEventListener('drop', (e) => {
    const file = e.dataTransfer.files[0];
    if (isValidCsv(file)) {
        readFile(file, 'slotRight', rightSlot);
    } else {
        console.error("Please drop a valid CSV file into the Right slot.");
    }
});

// Helper to validate if the dropped item is a CSV
function isValidCsv(file) {
    return file && (file.type === "text/csv" || file.name.endsWith('.csv'));
}

// Function 1: Handle reading the dropped file
function readFile(file, slotName, slotElement) {
    const reader = new FileReader();
    slotElement.textContent = `Loading File`;
    reader.onload = function (e) {
        const textContent = e.target.result;

        // Update the UI immediately to show the filename
        slotElement.textContent = `Reading File: ${file.name}`;
        convertCsvToArray(textContent, slotName);

        // Pass the data to the converter
        slotElement.textContent = `File: ${file.name}`;
        slotElement.classList.add('has-file');
    };

    reader.onerror = function () {
        console.error(`Error reading file for ${slotName}:`, reader.error);
    };

    reader.readAsText(file);
}

// Function 2: Convert CSV string to the requested format and replace in global memory
function convertCsvToArray(csvText, slotName) {
    let lines = csvText.split(/\r?\n/).filter(line => line.trim() !== '');
    const boilerPlate = "Generated by WizTree"
    if (lines.length === 0) {
        console.warn(`The dropped CSV file for ${slotName} is empty.`);
        window.csvDataStore[slotName] = null; // Clear previous if empty
        return;
    }
    if (lines[0].slice(0, boilerPlate.length) == boilerPlate) {
        console.log("reading wizTree csv file with boilerplate line")
        lines = lines.slice(1)
    }
    // Helper to parse CSV rows properly (handles commas inside quotes)
    const parseRow = (rowText) => {
        const result = [];
        let current = '';
        let inQuotes = false;

        for (let i = 0; i < rowText.length; i++) {
            const char = rowText[i];
            if (char === '"') {
                inQuotes = !inQuotes;
            } else if (char === ',' && !inQuotes) {
                result.push(current.trim());
                current = '';
            } else {
                current += char;
            }
        }
        result.push(current.trim());
        return result;
    };

    // const lens={}
    const allHeaders = parseRow(lines[0]);
    // lens[headers.length]=1;
    const data2D = [];
    for (let i = 1; i < lines.length; i++) {
        const row = parseRow(lines[i]);
        // lens[row.length]=1+lens[row.length]||0;
        data2D.push(row);
    }
    const headers = allHeaders.slice(0, data2D[1].length)
    const extraHeaders = allHeaders.slice(data2D[1].length)
    const extraDataValue = data2D[0].slice(data2D[1].length)
    const extraData = {}
    for (let i = 0; i < extraHeaders.length; i++) {
        const key = extraHeaders[i];
        const value = extraDataValue[i];
        extraData[key] = value;
    }

    // function pickAndShuffle(array, count) {
    //     for (let i = 0; i < count; i++) {
    //         const ind1=Math.floor(Math.random()*array.length);
    //         const ind2=Math.floor(Math.random()*array.length);
    //         const t=array[ind1];
    //         array[ind1]=array[ind2];
    //         array[ind2]=t;
    //         console.log(ind1,ind2)
    //     }
    // }
    // pickAndShuffle(data2D,4000)
    // console.log(lens)
    // Overwrite the specific slot in global storage with the new object structure
    window.csvDataStore[slotName] = {
        headers: headers,
        data: data2D,
        extraData: extraData,
    };

    console.log(`Updated window.csvDataStore.${slotName}:`, window.csvDataStore[slotName]);
}

function csvToTree(csvData) {
    const rootNodes = [];
    const nodeMap = new Map();

    // Helper to split Windows paths correctly and filter out empty strings
    const splitPath = (path) => path.split('\\').filter(part => part.length > 0);
    const retryNodes = []
    for (const row of csvData) {
        if (!row || row.length === 0) continue;

        const fullPath = row[0];
        const pathParts = splitPath(fullPath);

        if (pathParts.length === 0) continue;

        // The last element of the split path is the folder/file name
        const nodeName = pathParts[pathParts.length - 1];

        // Build the node structure
        const node = {
            name: nodeName,
            //   path: fullPath,
            // Store the rest of the columns as node data
            data: row.slice(1),
            children: []
        };

        // Keep track of this node by its full path for quick lookup
        nodeMap.set(fullPath, node);

        // Determine the parent path by removing the trailing slash and the last directory
        // e.g., "C:\Users\Alan George\AppData\" -> "C:\Users\Alan George\"
        const normalizedPath = fullPath.endsWith('\\') ? fullPath.slice(0, -1) : fullPath;
        const lastBackslash = normalizedPath.lastIndexOf('\\');

        if (lastBackslash === -1) {
            // It's a root drive like "C:"
            rootNodes.push(node);
        } else {
            const parentPath = normalizedPath.substring(0, lastBackslash + 1);
            const parentNode = nodeMap.get(parentPath);

            if (parentNode) {
                parentNode.children.push(node);
            } else {
                // Fallback: If the parent wasn't processed yet, it's treated as a root node
                retryNodes.push([node, fullPath]);
                // rootNodes.push(node);
            }
        }
    }
    let lastRetyListLength = 0;
    while (lastRetyListLength != retryNodes.length) {
        lastRetyListLength = retryNodes.length
        for (let i = retryNodes.length - 1; i >= 0; i--) {
            const node = retryNodes[i][0];
            const fullPath = retryNodes[i][1];

            // Determine the parent path by removing the trailing slash and the last directory
            // e.g., "C:\Users\Alan George\AppData\" -> "C:\Users\Alan George\"
            const normalizedPath = fullPath.endsWith('\\') ? fullPath.slice(0, -1) : fullPath;
            const lastBackslash = normalizedPath.lastIndexOf('\\');

            const parentPath = normalizedPath.substring(0, lastBackslash + 1);
            const parentNode = nodeMap.get(parentPath);

            if (parentNode) {
                parentNode.children.push(node);
                retryNodes.splice(i, 1)
            } else {
                // Fallback: If the parent wasn't processed yet, it's treated as a root node
                // retryNodes.push(node);
                // rootNodes.push(node);
            }
        }
    }
    for (let i = retryNodes.length - 1; i >= 0; i--) {
        const node = retryNodes[i][0];
        const fullPath = retryNodes[i][1];
        node['path'] = fullPath
        rootNodes.push(node);
    }
    sortChildrenDfs(rootNodes[0])
    return rootNodes;
}
function addChildToDiffTree(tree, paths, log) {
    if (paths[0] != tree.name) {
        throw new Error("Root Mismatch");
    }
    let currNode = { name: "", children: [tree] };
    for (let i = 0; i < paths.length; i++) {
        const path = paths[i];
        let matchIndex = -1;
        for (let j = 0; j < currNode.children.length; j++) {
            if (path == currNode.children[j].name) {
                matchIndex = j;
                break;
            }
        }
        if (matchIndex == -1) {
            let newNode = { "name": path, children: [] }
            matchIndex = currNode.children.length;
            currNode.children.push(newNode);
        }
        currNode = currNode.children[matchIndex];
        if (i == paths.length - 1) {
            if (currNode.log !== undefined) {
                throw new Error("Log OVERWRITE");
            }
            currNode.log = log
        }
    }
}
function sortChildrenDfs(node, resolver) {
    function _sortChildrenDfs(node, resolver) {
        if (node == undefined) return;
        node.children.sort(resolver)
        for (let i = 0; i < node.children.length; i++) {
            _sortChildrenDfs(node.children[i], resolver);
        }
    }
    if (resolver == undefined) {
        _sortChildrenDfs(node, (a, b) => a.name.localeCompare(b.name));
    }
    else {
        _sortChildrenDfs(node, resolver);
    }
}
function findInTree(tree, paths) {
    let currNode = tree
    if (paths[0] != tree.name) {
        return;
    }
    for (let i = 1; i < paths.length; i++) {
        const path = paths[i];
        for (let j = 0; j < currNode.children.length; j++) {
            const treeElement = currNode.children[j];
            if (treeElement.name == path) {
                currNode = treeElement;
                break;
            }
            else if (j == currNode.children.length - 1) {
                return;
            }
        }
    }
    return currNode
}
function findTreeDifferences(oldRootNode, newRootNode) {
    const differences = [];
    const allocatedHeaderIndex = 1
    const report = (type, path, details) => {
        differences.push({ type, path, ...details });
    };
    const pathJoin = (x, y) => `${x}\\${y.name}`
    function walk(oldTree, newTree, currentPath) {
        if (!oldTree && !newTree) return;

        if (oldTree && !newTree) {
            report("DELETED", currentPath, { name: oldTree.name, allocated: Number(oldTree.data[allocatedHeaderIndex]) });
            return;
        }

        if (!oldTree && newTree) {
            report("ADDED", currentPath, { name: newTree.name, node: newTree, allocated: Number(newTree.data[allocatedHeaderIndex]) });
            return;
        }
        const oldSize = Number(oldTree.data[allocatedHeaderIndex]), newSize = Number(newTree.data[allocatedHeaderIndex])
        if (newSize != oldSize) {
            report("CHANGED", currentPath, { name: newTree.name, node: newTree, allocated: newSize - oldSize });
        }

        const oldChildren = oldTree.children || [];
        const newChildren = newTree.children || [];

        let i = 0;
        let j = 0;

        while (i < oldChildren.length || j < newChildren.length) {
            const childOld = oldChildren[i];
            const childNew = newChildren[j];

            if (!childOld) {
                walk(null, childNew, pathJoin(currentPath, childNew));
                j++;
                continue;
            }

            if (!childNew) {
                walk(childOld, null, pathJoin(currentPath, childOld));
                i++;
                continue;
            }

            // Use localeCompare instead of < or > operators
            const comparison = childOld.name.localeCompare(childNew.name);

            if (comparison === 0) {
                // Names match perfectly, walk down into their children
                walk(childOld, childNew, pathJoin(currentPath, childOld));
                i++;
                j++;
            } else if (comparison < 0) {
                // childOld comes BEFORE childNew according to localeCompare.
                // This means childOld was deleted from the new tree.
                walk(childOld, null, pathJoin(currentPath, childOld));
                i++;
            } else {
                // childOld comes AFTER childNew according to localeCompare.
                // This means childNew is a brand-new node added to the tree.
                walk(null, childNew, pathJoin(currentPath, childNew));
                j++;
            }
        }
    }

    walk(oldRootNode, newRootNode, oldRootNode.name);
    return differences;
}
function computeAllocationDifference(node) {
    /* 
        instead of only total allocation difference, i also wanna show the total allocated and deallocated value

        the idea is to dfs to the leaf node of diffTree , not regular tree
        and then return the alloc-only and dealloc-only values to parent's caller where it gets summed up,
        btw deallocs are saved in negative on diffTree, no need to change to positive for this ig??
    */
    let allocations = 0, deallocations = 0;
    if (node.children.length > 0) {
        for (let i = 0; i < node.children.length; i++) {
            const child = node.children[i];
            const res = computeAllocationDifference(child)
            allocations += res[0];
            deallocations += res[1];
        }
        node.computedAllocation = allocations;
        node.computedDeallocation = deallocations;
    }
    else {// is leaf
        if (node.log.type == "DELETED") {
            deallocations -= node.log.allocated;
        }
        else if (node.log.allocated < 0) {
            deallocations += node.log.allocated;
        }
        else {
            allocations += node.log.allocated;
        }
    }
    return [allocations, deallocations]
}
function generateDiffTree(diffs) {
    const newTree = {
        "name": diffs[0].path.split("\\")[0],
        "children": []
    };
    for (let i = 0; i < diffs.length; i++) {
        const diff = diffs[i];
        addChildToDiffTree(newTree, diff.path.split("\\"), diff);
    }
    return newTree;
}

window.renderedTreeCollapseFunctions = []
function renderDiffTree(treeNode) {
    window.renderedTreeCollapseFunctions.length = 0;
    // Helper to format byte sizes into readable strings (e.g., GB, MB)
    function formatBytes(bytes) {
        if (bytes === 0) return "0 B";
        const absBytes = Math.abs(bytes);
        const k = 1024;
        const sizes = ["B", "KB", "MB", "GB", "TB"];
        const i = Math.floor(Math.log(absBytes) / Math.log(k));
        const formattedNum = parseFloat((absBytes / Math.pow(k, i)).toFixed(2));
        return `${bytes < 0 ? "-" : ""}${formattedNum} ${sizes[i]}`;
    }

    // Recursive element generator
    function createNodeElement(node) {
        const li = document.createElement("li");
        li.classList.add("diff-node");

        // Determine if it's an addition or deletion based on allocation
        // const isNegative = node.log?(node.log.allocated < 0):false;
        // if (node.log && node.log.allocated < 0){
        //     isNegative=true
        // }

        // li.classList.add(isNegative ? "diff-negative" : "diff-positive");
        let diffType = "diff-positive";
        if (node.log !== undefined) {
            if (node.log.type == "ADDED") {
                diffType = "diff-added";
            }
            else if (node.log.type == "DELETED") {
                diffType = "diff-deleted";
            }
            else if (node.log.type == "CHANGED") {
                if (node.log.allocated < 0) {
                    diffType = "diff-negative";
                }
            }
        }
        li.classList.add(diffType);

        // Row layout container
        const row = document.createElement("div");
        row.classList.add("diff-row");

        // Toggle arrow for directories with children
        const hasChildren = node.children && node.children.length > 0;
        const arrow = document.createElement("span");
        arrow.classList.add("diff-arrow");
        if (hasChildren) {
            arrow.classList.add("has-children", "expanded");
            arrow.textContent = "▼";
        } else {
            arrow.textContent = "•";
        }
        row.appendChild(arrow);

        // Name label
        const nameSpan = document.createElement("span");
        nameSpan.classList.add("diff-name");
        nameSpan.textContent = node.name;
        row.appendChild(nameSpan);

        // Allocation badge
        const allocSpan = document.createElement("span");
        allocSpan.classList.add("diff-allocation");
        allocSpan.textContent = formatBytes(node.log ? node.log.allocated : 0);
        row.appendChild(allocSpan);

        li.appendChild(row);

        // If it has children, build the nested list
        if (hasChildren) {
            const ul = document.createElement("ul");
            ul.classList.add("diff-children");

            node.children.forEach(child => {
                ul.appendChild(createNodeElement(child));
            });

            li.appendChild(ul);
            const collapseFunction = (toOpen) => {
                if (toOpen === undefined) {
                    const isCollapsed = ul.style.display === "none";
                    ul.style.display = isCollapsed ? "block" : "none";
                    arrow.textContent = isCollapsed ? "▼" : "▶";
                    arrow.classList.toggle("expanded", isCollapsed);
                }
                else if (toOpen === true) {
                    ul.style.display = "block";
                    arrow.textContent = "▼";
                    arrow.classList.toggle("expanded", false);
                }
                else if (toOpen === false) {
                    ul.style.display = "none";
                    arrow.textContent = "▶";
                    arrow.classList.toggle("expanded", true);
                }
            }
            window.renderedTreeCollapseFunctions.push(collapseFunction)
            // Simple click event to expand/collapse directories
            row.addEventListener("click", (e) => {
                // Prevent click if user is trying to select text
                if (window.getSelection().toString()) return;
                collapseFunction()
                // const isCollapsed = ul.style.display === "none";
                // ul.style.display = isCollapsed ? "block" : "none";
                // arrow.textContent = isCollapsed ? "▼" : "▶";
                // arrow.classList.toggle("expanded", isCollapsed);
            });
        }

        return li;
    }

    // Main container wrapper
    const container = document.createElement("div");
    container.classList.add("diff-tree-container");
    container.id = "diff-tree";

    const rootUl = document.createElement("ul");
    rootUl.classList.add("diff-root");
    rootUl.appendChild(createNodeElement(treeNode));

    container.appendChild(rootUl);
    return container;
}

function sortDiffTreeBySize(tree) {
    sortChildrenDfs(tree, (a, b) => -((a.log ? a.log.allocated : 0) - (b.log ? b.log.allocated : 0)));
}

function fullExpand() {
    renderedTreeCollapseFunctions.forEach((x)=>x(true))
}
function fullCollapse() {
    renderedTreeCollapseFunctions.forEach((x)=>x(false))
}